db.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
db.user=postgres.hlwysjzieukpycdniaab
db.password=EL20vbLYaZnMmGZy
db.driver=org.postgresql.Driver
horaCheckIn=15
horaCheckOut=12
iva.rate=0.19
